name: Issue Greeter

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  greet-issue-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Process issue description
        id: process-description
        run: python process_issue.py
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}

      - name: Create comment
        run: echo ${{ env.RESPONSE }}


